[project]
name = "expense-tracker-remote-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NaiduSudikhya", email = "naidu.sudikhya@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=3.4.7",
]

[project.scripts]
expense-tracker-remote-mcp = "expense_tracker_remote_mcp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
